[package]
name = "atlas-of-beancounting"
version = "0.1.0"
authors = ["Mordecai Malignatus <az4reus@gmail.com>"]

[dependencies]
notify = "4.0.6"
web-view = "0.2.1"
clipboard = "0.5.0"
chrono = "0.4.6"
regex = "1"
lazy_static = "1.1.0"
hyper = "0.12"