* Path of Beancounting

Ever been curious about what the numbers we all like so much actually look like
behind your mapping? Cool, me too.

* Things to be done
** TODO Look at notify package for the zone log
*** TODO Try to guess where the file is before prompting for config [/]
- [ ] Steam path
- [ ] Standalone-launcher path
*** TODO Look at how to structure the tail log for the zone log.
** TODO How is the data in the end going to be structured?
It's probably not going to be /that much/ data, so I could realistically store
it all in a JSON file and keep it in memory.

Another alternative is SQLite.
** TODO Find way to grab and cache the poe.ninja prices
** TODO Devise rudimentary item parser that extracts names and kinds.
** TODO Use InputBot to catch and handle user input on separate thread
https://github.com/obv-mikhail/InputBot

This will probably add another thread that has to be handled to the picture, for
hotkeys and "start new map" things.
* Things done.
** DONE Look at ~rust-webview~ for the UI parts.
CLOSED: [2018-10-04 Thu 05:55]
win-clipboard looks like a strong contender.
* About the Project

** Why is this being written?
I don't like uploading data like that to a centralised service for no good
reason, so here's something that works entirely machine-local, doesn't snoop for
anything, and doesn't consume too many resources.
